"""initial schema

Revision ID: 19b7bec01c76
Revises: 
Create Date: 2026-09-04 10:25:36.831303
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19b7bec01c76'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty',
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('registry_class', sa.String(length=64), nullable=True),
    sa.Column('registry_id', sa.String(length=128), nullable=True),
    sa.Column('jurisdiction', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('identity_key', sa.String(length=256), nullable=False),
    sa.Column('first_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('counterparty_id'),
    sa.UniqueConstraint('identity_key')
    )
    op.create_table('import_batch',
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('source_format', sa.String(length=8), nullable=False),
    sa.Column('file_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=320), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('import_batch_id')
    )
    op.create_index(op.f('ix_import_batch_file_fingerprint'), 'import_batch', ['file_fingerprint'], unique=False)
    op.create_table('person',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=320), nullable=False),
    sa.Column('identity_key', sa.String(length=256), nullable=True),
    sa.Column('first_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index('uq_person_identity_key', 'person', ['identity_key'], unique=True, postgresql_where=sa.text('identity_key IS NOT NULL'))
    op.create_table('identifier',
    sa.Column('identifier_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('id_type', sa.String(length=64), nullable=False),
    sa.Column('id_value', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.counterparty_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('identifier_id')
    )
    op.create_table('investigation',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('company_label', sa.String(length=512), nullable=False),
    sa.Column('contact_label', sa.String(length=512), nullable=False),
    sa.Column('intake_state', sa.Enum('SUFFICIENT_FOR_DISCOVERY', 'CLARIFICATION_REQUIRED', name='intakestate', native_enum=False, length=40), nullable=False),
    sa.Column('clarification_reason', sa.Text(), nullable=True),
    sa.Column('investigation_state', sa.Enum('NOT_STARTED', 'RUNNING', 'PARTIAL_RESULTS', 'SOURCE_UNAVAILABLE', 'COMPLETED', 'FAILED', name='investigationstate', native_enum=False, length=40), nullable=False),
    sa.Column('company_identity_status', sa.Enum('CONFIRMED', 'AMBIGUOUS', 'NOT_VERIFIED', name='companyidentitystatus', native_enum=False, length=40), nullable=True),
    sa.Column('company_match_basis', sa.Text(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('completeness_state', sa.Enum('COMPLETE', 'COMPLETE_WITH_LIMITATIONS', 'MATERIAL_SOURCE_UNAVAILABLE', name='completenessstate', native_enum=False, length=40), nullable=True),
    sa.Column('screening_state', sa.Enum('NO_MATERIAL_MATCH', 'POTENTIAL_MATCH', 'MATCH_REQUIRES_REVIEW', 'CONFIRMED_MATCH', name='screeningstate', native_enum=False, length=40), nullable=True),
    sa.Column('case_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.counterparty_id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.import_batch_id'], ),
    sa.PrimaryKeyConstraint('investigation_id'),
    sa.UniqueConstraint('import_batch_id', 'source_row_ref', name='uq_import_batch_row')
    )
    op.create_table('analyst_decision',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_ref', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('audit_event',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.Enum('INVESTIGATION_CREATED', 'REQUEST_CLARIFICATION', 'CLARIFICATION_SUPPLIED', 'RESOLVE_IDENTITY', 'LINK_COUNTERPARTY', 'CONFIRM_FINDING', 'DISMISS_FINDING', 'REQUEST_INFORMATION', 'ADD_NOTE', 'FINALISE_REPORT', 'STATE_CHANGE', 'IMPORT_BATCH_CREATED', name='auditaction', native_enum=False, length=48), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('target_ref', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('claim',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('subject_ref', sa.Uuid(), nullable=True),
    sa.Column('claim_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Enum('COMPANY', 'PERSON', 'DOMAIN', 'RELATIONSHIP', name='claimsubject', native_enum=False, length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asserted_by', sa.Enum('COUNTERPARTY', 'SOURCE', 'SYSTEM', name='assertedby', native_enum=False, length=40), nullable=False),
    sa.Column('assertion_origin_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('finding',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('finding_type', sa.Enum('CONTRADICTION', 'INCONSISTENCY', 'UNVERIFIED_CLAIM', 'ANOMALY', 'INSUFFICIENT_EVIDENCE', name='findingtype', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('assessment_text', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('related_claim_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('related_evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('review_status', sa.Enum('OPEN', 'CONFIRMED', 'DISMISSED', 'INFO_REQUESTED', name='reviewstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus', native_enum=False, length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_job_run_after'), 'job', ['run_after'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_table('person_candidate',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('label_fragment', sa.String(length=512), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('person_evidence_status', sa.Enum('IDENTITY_EVIDENCE_FOUND', 'LIMITED_EVIDENCE', 'IDENTITY_AMBIGUOUS', 'NO_RELIABLE_EVIDENCE_LOCATED', name='personevidencestatus', native_enum=False, length=40), nullable=True),
    sa.Column('relationship_state', sa.Enum('VERIFIED', 'CORROBORATED', 'SELF_ASSERTED', 'UNVERIFIED', 'CONTRADICTED', name='relationshipstate', native_enum=False, length=40), nullable=True),
    sa.Column('match_basis', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('source',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('source_class', sa.Enum('CORPORATE_REGISTRY', 'SANCTIONS_PEP_SCREENING', 'DOMAIN_REGISTRATION', 'OFFICIAL_PUBLICATION', 'COUNTERPARTY_ASSERTED', 'PRESS_MEDIA', 'WEB_PUBLIC', 'ANALYST_SUPPLIED', name='sourceclass', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('origin_ref', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('captured_by', sa.String(length=64), nullable=False),
    sa.Column('content_ref', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('license_class', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['source.source_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('observed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('extracted_by', sa.String(length=64), nullable=False),
    sa.Column('extraction_confidence', sa.Enum('AUTHORITATIVE', 'REPORTED', 'INFERRED', name='extractionconfidence', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('relationship',
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('person_candidate_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('VERIFIED', 'CORROBORATED', 'SELF_ASSERTED', 'UNVERIFIED', 'CONTRADICTED', name='relationshipstate', native_enum=False, length=40), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.counterparty_id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.ForeignKeyConstraint(['person_candidate_id'], ['person_candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    op.create_table('screening_result',
    sa.Column('screening_result_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('subject_label', sa.String(length=320), nullable=False),
    sa.Column('list_or_source', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('NO_MATERIAL_MATCH', 'POTENTIAL_MATCH', 'MATCH_REQUIRES_REVIEW', 'CONFIRMED_MATCH', name='screeningstate', native_enum=False, length=40), nullable=False),
    sa.Column('match_basis', sa.Text(), nullable=True),
    sa.Column('provider_event_group', sa.String(length=128), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.investigation_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], ),
    sa.PrimaryKeyConstraint('screening_result_id')
    )
    op.create_table('claim_evidence_link',
    sa.Column('link_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('SUPPORTS', 'CONTRADICTS', 'PARTIALLY_SUPPORTS', 'CONTEXT', name='linkrelation', native_enum=False, length=40), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.claim_id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_evidence_link')
    op.drop_table('screening_result')
    op.drop_table('relationship')
    op.drop_table('evidence')
    op.drop_table('source')
    op.drop_table('person_candidate')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_run_after'), table_name='job')
    op.drop_table('job')
    op.drop_table('finding')
    op.drop_table('claim')
    op.drop_table('audit_event')
    op.drop_table('analyst_decision')
    op.drop_table('investigation')
    op.drop_table('identifier')
    op.drop_index('uq_person_identity_key', table_name='person', postgresql_where=sa.text('identity_key IS NOT NULL'))
    op.drop_table('person')
    op.drop_index(op.f('ix_import_batch_file_fingerprint'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_table('counterparty')
    # ### end Alembic commands ###
